name: Build and deploy .NET Core application to Web App beertasting
on:
  workflow_run:
    workflows: ["Build"]
    types: [requested]
    branches:
    - main
  push:
    branches:
    - main
env:
  AZURE_WEBAPP_NAME: beertasting
  AZURE_WEBAPP_PACKAGE_PATH: .\published
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 7.0.x
  WORKING_DIRECTORY: .
jobs:
  build:
    runs-on: windows-latest
    env:
      BOB_SECRET: ${{ secrets.APPSETTINGSJSON }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Find and replace all instances of appsettings.json with the secret APPSETTINGSJSON
        run: |
          $files = Get-ChildItem -Path $PSScriptRoot -Filter appsettings.json -File -Recurse
          foreach ($file in $files){
              (Get-Content -path $file.FullName -Raw) -replace '.*', '${{ secrets.APPSETTINGSJSON }}' | Set-Content -Path $file.FullName
          }
      - name: Restore
        run: dotnet restore beertasting.sln
      - name: Build
        run: dotnet build beertasting.sln --configuration ${{ env.CONFIGURATION }}
      - name: Test
        run: dotnet test beertasting.sln --no-build
      - name: Publish
        run: dotnet publish beertasting.sln --configuration ${{ env.CONFIGURATION }} --no-build --output "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"
      - name: Publish Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: webapp
          path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
  deploy:
    runs-on: windows-latest
    needs: build
    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v2
      with:
        name: webapp
        path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
    - name: Deploy to Azure WebApp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.beertasting_32BB }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
